on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n clustescrud -g clustescrud814a-rg --location "West US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n clustescrud --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n clustescrud --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n clustescrud --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: clustescrud.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "DockerFile" -t clustescrud.azurecr.io/victorcluster:${{ github.sha }} --label dockerfile-path=DockerFile
        docker push clustescrud.azurecr.io/victorcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_victorcluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep clusterdb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace clusterdb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: clusterdb
        container-registry-url: clustescrud.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: victorclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: clusterdb
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          clustescrud.azurecr.io/victorcluster:${{ github.sha }}
        imagepullsecrets: |
          victorclustedockerauth   
